version: '3.7'
services:
  db:
    container_name: dockerdb
    image: mongo:4.2
    ports:
      - 27017:27017
  dev:
    container_name: theapp
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/local
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      DB_HOSTNAME: dockerdb
