version: '3.7'
services:
  dev:
    # image: nginx:alpine
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../app:/usr/share/nginx/html
    network_mode: "bridge"
    stdin_open: true # docker run -i
    tty: true        # docker run -t